target="template_release"
debug_symbols="no"
optimize="size"
lto="full"
module_text_server_adv_enabled="yes"
module_text_server_fb_enabled="yes"
deprecated="no"  # Disables deprecated features
vulkan="yes"      # Disables the Vulkan driver (used in Forward+/Mobile Renderers)
use_volk="no"    # Disables more Vulkan stuff
openxr="no"      # Disables Virtual Reality/Augmented Reality stuff
minizip="yes"     # Disables ZIP archive support
disable_3d="no"